version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: 'wurstmeister/kafka:2.12-2.2.1'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - zookeeper
      - kafka
    command: zookeeper:2181 kafka:9092
